import { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, Camera, Check, FileText, ImagePlus, Pencil, Plus, Save, Trash2, Upload, X } from "lucide-react";
import { createDocument, deleteDocument, generateBill, getDealWorkspace, readFileAsDataUrl, saveDealWorkflow, updateDocument } from "@/metroApi";

const tabs = ["Vehicle", "Seller", "Buyer", "Witnesses", "Payments", "Files"];
const vehicleFields = [["vehicle_name", "Vehicle Name"], ["make", "Make"], ["model", "Model"], ["year_of_manufacture", "Year"], ["color", "Color"], ["engine_number", "Engine Number"], ["chassis_number", "Chassis Number"], ["vehicle_number", "Vehicle Number"], ["registration_number", "Registration Number"], ["insurance", "Insurance"]];
const emptyPerson = { name: "", phone: "", address: "", id_details: "", photo: null };
const emptyPayment = { person: "", payment_type: "Purchase", amount: "", payment_date: new Date().toISOString().slice(0, 10), payment_status: "Pending", notes: "" };

export default function FunctionalNewDeal() {
  const { dealId: routeDealId } = useParams();
  const navigate = useNavigate();
  const [tab, setTab] = useState("Vehicle");
  const [dealId, setDealId] = useState(routeDealId || "");
  const [deal, setDeal] = useState({ deal_type: "Buy & Sell", status: "Draft" });
  const [vehicle, setVehicle] = useState({ vehicle_name: "", make: "", model: "", year_of_manufacture: "", color: "", engine_number: "", chassis_number: "", vehicle_number: "", registration_number: "", insurance: "" });
  const [seller, setSeller] = useState(emptyPerson);
  const [buyer, setBuyer] = useState(emptyPerson);
  const [witnesses, setWitnesses] = useState([]);
  const [payments, setPayments] = useState([]);
  const [documents, setDocuments] = useState([]);
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const fileInput = useRef(null);

  useEffect(() => { if (!routeDealId) return; setBusy(true); getDealWorkspace(routeDealId).then(loadWorkspace).catch(error => setMessage(error.message)).finally(() => setBusy(false)); }, [routeDealId]);
  function loadWorkspace(workspace) {
    setDealId(workspace.deal.deal_id); setDeal(workspace.deal); setVehicle(workspace.vehicle); setSeller(workspace.seller || emptyPerson); setBuyer(workspace.buyer || emptyPerson); setWitnesses(workspace.witnesses || []); setPayments(workspace.payments || []); setDocuments(workspace.documents || []);
  }
  const setVehicleField = (key, value) => setVehicle(current => ({ ...current, [key]: key === "year_of_manufacture" ? value.replace(/\D/g, "") : value }));
  const save = async () => { setBusy(true); setMessage(""); try { const workspace = await saveDealWorkflow({ deal_id: dealId || undefined, ...deal, vehicle: { ...vehicle, year_of_manufacture: Number(vehicle.year_of_manufacture) || 0 }, seller: { ...seller, photo: seller.photo || undefined }, buyer: { ...buyer, photo: buyer.photo || undefined }, witnesses: witnesses.map(({ witness_id, deal_id: ignoredDeal, ...person }) => person), payments: payments.map(({ payment_id, deal_id: ignoredDeal, created_date, updated_date, ...payment }) => ({ ...payment, amount: Number(payment.amount) || 0 })) }); loadWorkspace(workspace); setMessage(`Saved Deal ${workspace.deal.deal_id}`); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  const addPersonPhoto = async (personKey, event) => { const file = event.target.files?.[0]; if (!file) return; const dataUrl = await readFileAsDataUrl(file); (personKey === "seller" ? setSeller : setBuyer)(person => ({ ...person, photo: dataUrl })); };
  const uploadDocuments = async (event, category = "Other") => { if (!dealId) { setMessage("Save the Deal before adding files."); return; } const files = [...(event.target.files || [])]; setBusy(true); try { const created = []; for (const file of files) { const reference = await readFileAsDataUrl(file); created.push(await createDocument({ deal_id: dealId, category, file_reference: reference, file_name: file.name, mime_type: file.type, file_size: file.size, document_kind: file.type.startsWith("image/") ? "photo" : "document" })); } setDocuments(current => [...current, ...created]); setMessage(`${created.length} file${created.length > 1 ? "s" : ""} linked to ${dealId}`); } catch (error) { setMessage(error.message); } finally { setBusy(false); event.target.value = ""; } };
  const replaceDocument = async (document, event) => { const file = event.target.files?.[0]; if (!file) return; const reference = await readFileAsDataUrl(file); const updated = await updateDocument(document.document_id, { file_reference: reference, file_name: file.name, mime_type: file.type, file_size: file.size }); setDocuments(current => current.map(item => item.document_id === document.document_id ? updated : item)); event.target.value = ""; };
  const removeDocument = async (documentId) => { await deleteDocument(documentId); setDocuments(current => current.filter(item => item.document_id !== documentId)); };
  const createBill = async (billType) => { if (!dealId) return setMessage("Save the Deal before generating a bill."); try { const bill = await generateBill(dealId, billType); setMessage(`${bill.bill_type} bill ${bill.bill_number} is ready`); } catch (error) { setMessage(error.message); } };
  const updateList = (setter, index, key, value) => setter(current => current.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item));
  const addWitness = () => setWitnesses(current => [...current, { ...emptyPerson }]);
  const addPayment = () => setPayments(current => [...current, { ...emptyPayment }]);
  return <><div className="deal-top"><button className="back-link" onClick={() => navigate(-1)} data-testid="new-deal-back"><ArrowLeft size={17}/> Back</button><div><div className="eyebrow">Deal workspace {dealId && `· ${dealId}`}</div><h1 data-testid="page-title">{dealId ? "Edit Deal" : "New Deal"}</h1></div><div className="deal-actions"><button className="button button-secondary" onClick={() => setMessage(`Viewing ${dealId || "unsaved deal"}`)} data-testid="view-deal-button"><FileText size={16}/> View Deal</button><button className="button button-primary" onClick={save} disabled={busy} data-testid="save-deal-button"><Save size={16}/> {busy ? "Saving..." : "Save Deal"}</button></div></div><div className="deal-tabs" role="tablist">{tabs.map((item, index) => <button className={tab === item ? "active" : ""} onClick={() => setTab(item)} role="tab" aria-selected={tab === item} data-testid={`new-deal-tab-${item.toLowerCase()}`} key={item}><span>{index + 1}</span>{item}</button>)}</div>{message && <div className="workflow-message" data-testid="workflow-message">{message}</div>}<section className="form-section"><div className="section-title"><div><h2>{tab} information</h2><p>{dealId ? `All changes stay connected to ${dealId}.` : "Complete the tabs, then save one connected transaction."}</p></div><span className="required-note">* Required fields</span></div>{tab === "Vehicle" && <VehiclePanel vehicle={vehicle} setField={setVehicleField}/>} {tab === "Seller" && <PersonPanel title="Seller" person={seller} setPerson={setSeller} onPhoto={event => addPersonPhoto("seller", event)}/>} {tab === "Buyer" && <PersonPanel title="Buyer" person={buyer} setPerson={setBuyer} onPhoto={event => addPersonPhoto("buyer", event)}/>} {tab === "Witnesses" && <WitnessPanel witnesses={witnesses} updateList={updateList} setWitnesses={setWitnesses} addWitness={addWitness}/>} {tab === "Payments" && <PaymentPanel payments={payments} updateList={updateList} setPayments={setPayments} addPayment={addPayment}/>} {tab === "Files" && <FilesPanel documents={documents} fileInput={fileInput} uploadDocuments={uploadDocuments} replaceDocument={replaceDocument} removeDocument={removeDocument} createBill={createBill}/>}</section></>;
}

function VehiclePanel({ vehicle, setField }) { return <><div className="photo-upload"><div className="photo-placeholder"><Camera size={22}/><b>Vehicle files are managed in Files</b><span>Save the Deal first, then add multiple photos or documents.</span></div></div><div className="form-grid">{vehicleFields.map(([key, label], index) => <label className="form-field" key={key}><span>{label}{index < 4 && <em>*</em>}</span>{key === "insurance" ? <select value={vehicle[key]} onChange={event => setField(key, event.target.value)} data-testid={`new-deal-${key}-input`}><option value="">Select insurance status</option><option>Active</option><option>Expired</option></select> : <input value={vehicle[key] || ""} onChange={event => setField(key, event.target.value)} placeholder={`Enter ${label.toLowerCase()}`} data-testid={`new-deal-${key}-input`}/>}</label>)}</div></> }
function PersonPanel({ title, person, setPerson, onPhoto }) { const fields = [["name", "Name"], ["phone", "Phone"], ["address", "Address"], ["id_details", "ID details"]]; return <><div className="form-grid">{fields.map(([key, label]) => <label className="form-field" key={key}><span>{label}<em>*</em></span><input value={person[key] || ""} onChange={event => setPerson(current => ({ ...current, [key]: event.target.value }))} data-testid={`${title.toLowerCase()}-${key.replace("_", "-")}-input`}/></label>)}</div><div className="person-photo-upload"><div className="person-photo-preview">{person.photo ? <img src={person.photo} alt={`${title} ID preview`}/> : <ImagePlus size={20}/>}</div><label className="button button-secondary" data-testid={`${title.toLowerCase()}-photo-input-label`}><Upload size={15}/> Upload photo<input hidden type="file" accept="image/*" onChange={onPhoto} data-testid={`${title.toLowerCase()}-photo-input`}/></label></div></> }
function WitnessPanel({ witnesses, updateList, setWitnesses, addWitness }) { return <><div className="repeatable-list">{witnesses.map((witness, index) => <div className="repeatable-row" key={index}><b>Witness {index + 1}</b>{["name", "phone", "address", "id_details"].map(key => <input key={key} value={witness[key] || ""} placeholder={key.replace("_", " ")} onChange={event => updateList(setWitnesses, index, key, event.target.value)} data-testid={`witness-${index}-${key}-input`}/>)}<button className="icon-button" onClick={() => setWitnesses(current => current.filter((_, itemIndex) => itemIndex !== index))} aria-label="Delete witness" data-testid={`delete-witness-${index}`}><Trash2 size={15}/></button></div>)}</div><button className="button button-secondary" onClick={addWitness} data-testid="add-witness-button"><Plus size={15}/> Add witness</button></> }
function PaymentPanel({ payments, updateList, setPayments, addPayment }) { return <><div className="repeatable-list">{payments.map((payment, index) => <div className="repeatable-row payment-row" key={index}><input value={payment.person || ""} placeholder="Person" onChange={event => updateList(setPayments, index, "person", event.target.value)} data-testid={`payment-${index}-person-input`}/><input value={payment.amount || ""} type="number" placeholder="Amount" onChange={event => updateList(setPayments, index, "amount", event.target.value)} data-testid={`payment-${index}-amount-input`}/><input value={payment.payment_type || ""} placeholder="Payment type" onChange={event => updateList(setPayments, index, "payment_type", event.target.value)} data-testid={`payment-${index}-type-input`}/><input value={payment.payment_date || ""} type="date" onChange={event => updateList(setPayments, index, "payment_date", event.target.value)} data-testid={`payment-${index}-date-input`}/><select value={payment.payment_status || "Pending"} onChange={event => updateList(setPayments, index, "payment_status", event.target.value)} data-testid={`payment-${index}-status-input`}><option>Pending</option><option>Paid</option><option>Partial</option></select><input value={payment.notes || ""} placeholder="Notes" onChange={event => updateList(setPayments, index, "notes", event.target.value)} data-testid={`payment-${index}-notes-input`}/><button className="icon-button" onClick={() => setPayments(current => current.filter((_, itemIndex) => itemIndex !== index))} aria-label="Delete payment" data-testid={`delete-payment-${index}`}><Trash2 size={15}/></button></div>)}</div><button className="button button-secondary" onClick={addPayment} data-testid="add-payment-button"><Plus size={15}/> Add payment</button></> }
function FilesPanel({ documents, fileInput, uploadDocuments, replaceDocument, removeDocument, createBill }) { const [category, setCategory] = useState("Vehicle"); return <><div className="file-toolbar"><select value={category} onChange={event => setCategory(event.target.value)} data-testid="file-category-select"><option>Vehicle</option><option>Seller</option><option>Buyer</option><option>Other</option></select><label className="button button-primary"><Upload size={15}/> Upload files<input ref={fileInput} hidden type="file" multiple onChange={event => uploadDocuments(event, category)} data-testid="deal-file-upload"/></label><label className="button button-secondary"><Camera size={15}/> Take photo<input hidden type="file" accept="image/*" capture="environment" onChange={event => uploadDocuments(event, category)} data-testid="deal-camera-upload"/></label></div><div className="document-grid" data-testid="deal-documents-grid">{documents.map(document => <div className="document-card" key={document.document_id}>{document.mime_type?.startsWith("image/") ? <img src={document.file_reference} loading="lazy" alt={document.file_name || document.category}/> : <div className="document-icon"><FileText size={24}/></div>}<b>{document.file_name || document.category}</b><span>{document.category}</span><div><label className="icon-button" title="Replace"><Pencil size={14}/><input hidden type="file" onChange={event => replaceDocument(document, event)} data-testid={`replace-document-${document.document_id}`}/></label><button className="icon-button" onClick={() => removeDocument(document.document_id)} aria-label="Delete document" data-testid={`delete-document-${document.document_id}`}><Trash2 size={14}/></button></div></div>)}{documents.length === 0 && <div className="empty-tab"><FileText size={24}/><p>No files linked yet. You can add 14 or more files across categories.</p></div>}</div><div className="bill-actions"><button className="button button-secondary" onClick={() => createBill("Seller → Intermediate")} data-testid="generate-intermediate-bill"><FileText size={15}/> Seller → Intermediate</button><button className="button button-primary" onClick={() => createBill("Seller → Buyer")} data-testid="generate-buyer-bill"><FileText size={15}/> Seller → Buyer</button></div></> }