const field = (key, label, type = "text", extra = {}) => ({ key, label, type, ...extra });
const select = (key, label, options) => field(key, label, "select", { options });
export const vehicleGroups = [
  { title: "Vehicle details", fields: [field("vehicle_name", "Vehicle name", "text", { required: true }), field("make", "Make / Brand", "text", { required: true }), field("model", "Model", "text", { required: true }), field("variant", "Variant"), field("year", "Year of manufacture", "number", { required: true, min: 1900, max: new Date().getFullYear() + 1 }), field("color", "Color"), field("vehicle_number", "Vehicle number", "text", { required: true }), field("registration_number", "Registration number"), field("registration_date", "Registration date", "date"), field("engine_number", "Engine number"), field("chassis_number", "Chassis number"), field("engine_cc", "Engine capacity (cc)", "number"), select("fuel_type", "Fuel type", ["Petrol", "Electric", "Diesel", "Other"]), select("transmission", "Transmission", ["Manual", "Automatic"]), field("odometer", "Odometer (km)", "number")] },
  { title: "Ownership & condition", fields: [select("ownership", "Ownership", ["First Owner", "Second Owner", "Third Owner", "Fourth Owner or More"]), select("condition", "Condition", ["Excellent", "Good", "Fair", "Needs Repair"]), field("bought_date", "Bought date", "date", { required: true }), field("sold_date", "Sold date", "date"), select("keys", "Number of keys", ["0", "1", "2", "3"]), field("service_history", "Service history")] },
  { title: "Documents & validity", fields: [select("tax", "Tax", ["Paid", "Pending", "Expired", "Lifetime"]), field("tax_valid_until", "Tax valid until", "date"), select("fitness", "Fitness", ["Valid", "Expired", "Pending"]), field("fitness_valid_until", "Fitness valid until", "date"), select("insurance", "Insurance", ["Active", "Expired", "Not Available"]), field("insurance_policy", "Insurance policy number"), field("insurance_valid_until", "Insurance valid until", "date"), field("puc_valid_until", "PUC valid until", "date"), select("hypothecation", "Hypothecation / Loan", ["No", "Yes", "Closed"]), field("financier", "Financier"), select("noc", "NOC", ["Not Required", "Available", "Pending"])] },
];
export const personFields = [field("name", "Full name"), field("father_name", "Father / Spouse name"), field("phone", "Mobile number", "tel"), field("alternate_phone", "Alternate mobile", "tel"), field("email", "Email address", "email"), field("address", "Address", "textarea"), field("city", "City / District"), field("state", "State"), field("pincode", "PIN code"), select("id_type", "ID type", ["Aadhaar", "Driving Licence", "Passport", "Voter ID", "Other"]), field("id_number", "ID number"), field("pan_number", "PAN number")];
export const dealerFields = [field("dealer_name", "Dealership name", "text", { required: true }), field("gst_number", "GST number"), field("dealer_address", "Dealership address", "textarea")];
export const witnessFields = [field("name", "Full name"), field("phone", "Mobile number", "tel"), field("address", "Address", "textarea"), field("id_number", "ID details")];
export const paymentFields = [field("purchase_price", "Purchase price (₹)", "number", { required: true, step: "0.01" }), field("selling_price", "Selling price (₹)", "number", { step: "0.01" }), field("paid_to_seller", "Paid to seller (₹)", "number", { step: "0.01" }), field("received_from_buyer", "Received from buyer (₹)", "number", { step: "0.01" }), select("payment_method", "Payment method", ["Cash", "UPI", "Bank Transfer", "Cheque", "Mixed"]), field("payment_date", "Payment date", "date"), field("transaction_reference", "Transaction reference"), field("notes", "Payment notes", "textarea")];
export const photoSlots = {
  vehicle: ["Front view", "Rear view", "Left side", "Right side", "Odometer", "Engine number", "Chassis number", "RC front", "RC back", "Insurance document"],
  seller: ["Seller portrait", "Aadhaar front", "Aadhaar back", "PAN card", "Driving licence front", "Driving licence back", "Address proof", "Signature", "Purchase agreement", "Additional document"],
  buyer: ["Buyer portrait", "Aadhaar front", "Aadhaar back", "PAN card", "Driving licence front", "Driving licence back", "Address proof", "Signature", "Sale agreement", "Additional document"],
  "witness-1": ["Seller witness photo"], "witness-2": ["Buyer witness photo"],
};